~Config
WarpSystem:
  Language: ENG
  Maintenance: false
  Admin:
    Permission: 'WarpSystem.Admin'

  GUI:
    # false: The WarpGUI is identical on the entire server in all worlds
    # true: The WarpGUI is different in every world
    Bound_to_world: false
    Admin:
      # The number must be between inclusive 9 and inclusive 54 and must be divisible by 9.
      Size: 54
      Title:
        Standard: '&c&l&nWarps&r'
        In_Category: '&c&l&nWarps&r &c@%CATEGORY%'
    User:
      # The number must be between inclusive 9 and inclusive 54 and must be divisible by 9.
      Size: 54
      Title:
        Standard: '&c&l&nWarps&r'
        In_Category: '&c&l&nWarps&r &c@%CATEGORY%'

  Teleport:
    Animation_After_Teleport:
      Enabled: true
    Delay: 5
    # Animations:
    # 0  - FIREWORKS_SPARK
    # 1  - SUSPENDED_DEPTH
    # 2  - CRIT
    # 3  - CRIT_MAGIC
    # 4  - SMOKE_NORMAL
    # 5  - SMOKE_LARGE
    # 6  - SPELL
    # 7  - SPELL_INSTANT
    # 8  - SPELL_MOB
    # 9  - SPELL_WITCH
    # 10 - DRIP_WATER
    # 11 - DRIP_LAVA
    # 12 - VILLAGER_ANGRY
    # 13 - VILLAGER_HAPPY
    # 14 - TOWN_AURA
    # 15 - NOTE
    # 16 - ENCHANTMENT_TABLE
    # 17 - FLAME
    # 18 - CLOUD
    # 19 - REDSTONE
    # 20 - SNOW_SHOVEL
    # 21 - HEART
    # 22 - PORTAL
    Animation: 17
    Allow_Move: false

  Send:
    Teleport_Message:
      WarpGUI: true
      SimpleWarps: true
      GlobalWarps: true
      NativePortals: true
      Portals: true
      WarpSigns: true
      TempWarps: true
      CommandBlocks: true
    Teleport_Cancel_Message: true

  Functions:
    Warps: true
    SimpleWarps: true
    Portals: true
    NativePortals: true
    WarpSigns: true
    GlobalWarps: true
    Shortcuts: true
    TempWarps: true
    #Available commands: '/warp <warp>' or '/globalwarp <warp>'
    #Activates when a player is within 5 blocks of a CommandBlock and the CommandBlock is active
    CommandBlocks: true
    RandomTeleport: true

  TempWarps:
    #Permission to set the available amount of TempWarps: "WarpSystem.TempWarps.2" (Example for a maximum of 2 TempWarps)
    Time:
      #sec, min, hour, day
      Interval: min
      #Step to increase/decrease the duration in the gui
      DurationSteps: 5
      Min_Time: 5
      Max_Time: 1440
    # When a TempWarp expires, then it's inactive. (When "Time_After_Expiration" is expired too, the TempWarp will be deleted.)
    Inactive:
      # Time in seconds after an expiration. After that time, the TempWarp will be deleted.
      Time_After_Expiration: 60
      # Time in seconds to remind a player, if a TempWarp is inactive
      Reminds:
      - 30
      - 10
      - 5
    Name:
      Edit_Costs: 50
    Refund: true
    Message:
      Min_character_length: 5
      Max_character_length: 50
      Refund_by_removing_message: 0
      Edit_Costs: 50
    Custom_Teleport_Costs:
      Max_Costs: 500
      #Step to increase/decrease costs in gui
      Cost_Steps: 50
      #Percent of custom TeleportCosts
      TeleportCosts: 50
    Costs:
      CostsPerInterval: 5
      PublicCosts: 5
      MessageCosts: 5
    Support:
      #If enabled, the player can't create TempWarps in regions, where he cannot build
      ProtectedRegions: false

  EffectPortals:
    #Max distance between particle and player
    ParticleDistance: 70.0

  Commands:
    Warp:
      #true: '/warp' opens the WarpGUI
      #false: '/warp <warp>' teleports you to warps
      GUI: false

  #The standard and max amount of random teleports will be configured with permissions:
  # "warpsystem.randomteleporters.free.1" » This permissions means, that the player with that permission has a standard amount of 1 free random teleports
  # "warpsystem.randomteleporters.max.2" » This permissions means, that the player with that permission has a max amount of 2 random teleports, so he could buy one, if it's enabled
  RandomTeleport:
    #Costs for one extra teleport (buyable with commands)
    Buyable:
      Enabled: true
      Costs: 500
    Range:
      Min: 1000
      Max: 10000
    Support:
      #If enabled, the player will be teleported to a random position, which is not in a protected region
      ProtectedRegions: true
      #If enabled, the player will be teleported to a random position, in one of the listed biomes
      Biome:
        Enabled: true
        #Names can be found here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/block/Biome.html
        BiomeList:
          - OCEAN
          - PLAINS
          - DESERT
          - EXTREME_HILLS
          - FOREST
          - TAIGA
          - SWAMPLAND
          - RIVER
          - HELL
          - SKY
          - FROZEN_OCEAN
          - FROZEN_RIVER
          - ICE_FLATS
          - ICE_MOUNTAINS
          - MUSHROOM_ISLAND
          - MUSHROOM_ISLAND_SHORE
          - BEACHES
          - DESERT_HILLS
          - FOREST_HILLS
          - TAIGA_HILLS
          - SMALLER_EXTREME_HILLS
          - JUNGLE
          - JUNGLE_HILLS
          - JUNGLE_EDGE
          - DEEP_OCEAN
          - STONE_BEACH
          - COLD_BEACH
          - BIRCH_FOREST
          - BIRCH_FOREST_HILLS
          - ROOFED_FOREST
          - TAIGA_COLD
          - TAIGA_COLD_HILLS
          - REDWOOD_TAIGA
          - REDWOOD_TAIGA_HILLS
          - EXTREME_HILLS_WITH_TREES
          - SAVANNA
          - SAVANNA_ROCK
          - MESA
          - MESA_ROCK
          - MESA_CLEAR_ROCK
